use_frameworks!

platform :ios, '12.0'

target 'TestVCPod_Example' do
  pod 'TestVCPod', :git => 'https://github.com/OksanaDychok/TestVCPod'

  target 'TestVCPod_Tests' do
    inherit! :search_paths

    
  end
end
